language: python
python:
  - "3.3"
env:
  matrix:
    - run=none         # gives 31%
    - run=all          # gives 99%
install:
  - "pip install -r requirements.txt"
  - pip install coveralls

script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - which python
  - coverage run `which nosetests` test.py --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage xml -o shippable/codecoverage/coverage.xml

after_success:
  coveralls
